version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - run:
          name: Start Job
          command: |
            wget https://raw.githubusercontent.com/Exynos-nigg/OrangeFox_device_samsung_dreamlte/pie/circle.sh && bash circle.sh 
      - store_artifacts:
          path: ~/output/

version: 2.1